-- Run this script in the Supabase SQL Editor.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', 'Reader'),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.books enable row level security;
alter table public.user_library enable row level security;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'profiles'
      and column_name = 'Privacy'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'profiles'
      and column_name = 'privacy'
  ) then
    alter table public.profiles rename column "Privacy" to privacy;
  end if;
end $$;

alter table public.profiles add column if not exists privacy text;
update public.profiles
set privacy = case when lower(trim(coalesce(privacy, ''))) = 'public'
  then 'public' else 'private' end;
alter table public.profiles alter column privacy set default 'private';
alter table public.profiles alter column privacy set not null;

revoke select on public.profiles from public, anon, authenticated;
grant select (id, username, role, picture, privacy)
  on public.profiles to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.profiles'::regclass
      and conname = 'profiles_privacy_check'
  ) then
    alter table public.profiles
      add constraint profiles_privacy_check check (privacy in ('public', 'private'));
  end if;
end $$;

alter table public.books
  alter column rate type numeric(3,1)
  using rate::numeric;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.user_library'::regclass
      and conname = 'user_library_user_book_unique'
  ) then
    alter table public.user_library
      add constraint user_library_user_book_unique unique (user_id, book_id);
  end if;
end $$;

create table if not exists public.user_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  book_id bigint not null,
  title text not null,
  note text not null,
  created_at timestamptz not null default now(),
  constraint user_notes_user_book_fkey
    foreign key (user_id, book_id)
    references public.user_library (user_id, book_id)
    on delete cascade
);
alter table public.user_notes
  drop constraint if exists user_notes_book_id_fkey;
alter table public.user_notes enable row level security;

create or replace function public.recalculate_book_rate(p_book_id bigint)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  update public.books
  set rate = coalesce((
    select round(avg(rate)::numeric, 1)
    from public.user_library
    where book_id = p_book_id
      and status::text = 'read'
      and rate > 0
  ), 0)
  where id = p_book_id;
end;
$$;

create or replace function public.refresh_book_rate_after_library_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.recalculate_book_rate(old.book_id);
    return old;
  end if;

  if tg_op = 'UPDATE' and old.book_id is distinct from new.book_id then
    perform public.recalculate_book_rate(old.book_id);
  end if;
  perform public.recalculate_book_rate(new.book_id);
  return new;
end;
$$;

drop trigger if exists refresh_book_rate on public.user_library;
create trigger refresh_book_rate
  after insert or update of status, rate, book_id or delete
  on public.user_library
  for each row execute procedure public.refresh_book_rate_after_library_change();

update public.books as books
set rate = coalesce((
  select round(avg(library.rate)::numeric, 1)
  from public.user_library as library
  where library.book_id = books.id
    and library.status::text = 'read'
    and library.rate > 0
), 0);

drop policy if exists "Users can view their profile" on public.profiles;
create policy "Users can view their profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Keep role changes out of the client API while allowing profile edits.
revoke update on public.profiles from authenticated;
grant update (username, picture, privacy) on public.profiles to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and lower(trim(coalesce(role, ''))) = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "Admins can view profiles" on public.profiles;
create policy "Admins can view profiles"
  on public.profiles for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Users can view public profiles" on public.profiles;
drop policy if exists "Users can view reader profiles" on public.profiles;
create policy "Users can view reader profiles"
  on public.profiles for select
  to authenticated
  using (lower(trim(coalesce(role, ''))) <> 'admin');

drop policy if exists "Authenticated users can view books" on public.books;
create policy "Authenticated users can view books"
  on public.books for select
  to authenticated
  using (true);

grant select, insert, update, delete on public.books to authenticated;
drop policy if exists "Admins can manage books" on public.books;
create policy "Admins can manage books"
  on public.books for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can manage book pictures" on storage.objects;
create policy "Admins can manage book pictures"
  on storage.objects for all
  to authenticated
  using (bucket_id = 'Book pictures' and public.is_admin())
  with check (bucket_id = 'Book pictures' and public.is_admin());

drop policy if exists "Users can manage their profile pictures" on storage.objects;
create policy "Users can manage their profile pictures"
  on storage.objects for all
  to authenticated
  using (
    bucket_id = 'profile pictures'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
  )
  with check (
    bucket_id = 'profile pictures'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
  );

drop policy if exists "Users can view their library" on public.user_library;
create policy "Users can view their library"
  on public.user_library for select
  using (auth.uid() = user_id);

drop policy if exists "Admins can view all user libraries" on public.user_library;
create policy "Admins can view all user libraries"
  on public.user_library for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Users can view public profile libraries" on public.user_library;
create policy "Users can view public profile libraries"
  on public.user_library for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = user_library.user_id
        and profiles.privacy = 'public'
    )
  );

drop policy if exists "Users can add to their library" on public.user_library;
create policy "Users can add to their library"
  on public.user_library for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their library" on public.user_library;
create policy "Users can update their library"
  on public.user_library for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant delete on public.user_library to authenticated;

drop policy if exists "Users can remove from their library" on public.user_library;
create policy "Users can remove from their library"
  on public.user_library for delete
  to authenticated
  using (auth.uid() = user_id);

grant select, insert, update, delete on public.user_notes to authenticated;

drop policy if exists "Users can view their notes" on public.user_notes;
create policy "Users can view their notes"
  on public.user_notes for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can add their notes" on public.user_notes;
create policy "Users can add their notes"
  on public.user_notes for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their notes" on public.user_notes;
create policy "Users can update their notes"
  on public.user_notes for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their notes" on public.user_notes;
create policy "Users can delete their notes"
  on public.user_notes for delete
  to authenticated
  using (auth.uid() = user_id);